version: '3'

services:
    mysql:
        image: mysql
        platform: 'linux/x86_64'
        command: --default-authentication-plugin=mysql_native_password --collation-server=utf8mb4_unicode_ci
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: laravel
            MYSQL_DATABASE: laravel

